# Dataset
class_names: ['Fine', 'Small', 'Large']

# Training
batch_size: 10  # batch size
lr: 2e-5  # learning rate
epochs: 10  # DBMSF coverages fast, no need for many epochs
iters_to_val: 1000  # set to -1 to validate per epoch
save_best: True

# Model
freeze_ratio: 1  # ratio of ViT blocks to freeze
cmb: ml  # in: s, m, l, sm, sl, ml, sml
UNI_path: '\..\'  # replace with your own path